### PR TITLE
Update api.py

### PR DESCRIPTION
**Pull request by sheepsy90**

### CODE REVIEW

**Comment by sheepsy90** [comment]
Quick question on this @chupakabra - Can you explain to me how it would work with the token check - i didn't looked into the django rest api framework yet

**Comment by sheepsy90** [comment]
Hey @chupakabra I looked into it a bit but it seemed to be a little to complex right now to adapt to a full framework - maybe we can do that if more other services are actually using apis

**Comment by daria-chernobaieva** [comment]
Yes I agree with you that all the changes should be reasonable. It was just example to take into account that it exists and can be applied if we need to work with API mostly. I only mentioned DRF to show what I mostly dealt with in the scope of work with Django. But it doesn't mean that I can't work in the scope of standard Django's MTV scheme. Anyway looking forward to some tasks from you.

**Comment by sheepsy90** [comment]
Hey @chupakabra - thanks for the feedback - did i understand you correctly that you would enjoy backend oriented tasks more then frontend? If so there is a the problem that location distances are currently only calculated when I run the management command under the location application. It would be great if we could change this in the backend in a way that whenever someone adds a location the necessary updates are done. Interesting with this is the runtime problem of all n - n connections (it should be all under locations - if you interested in fixing this we can create an issue for this and you can do this :)

**Comment by daria-chernobaieva** [comment]
Hey, I wouldn't say that I enjoy it, but I mostly have experience with back-end part indeed. So, I'd like to try to solve this location issue that you described.

**Comment by sheepsy90** [comment]
@chupakabra  I added a ticket https://github.com/sheepsy90/django-rbe/issues/44

**Pull request closed without merging**
